# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9ce40eeba8c10c0fb36d33e00edcfa87d46462c36473a498d1f731516a052594ff911657999fe40a89a7c39e656fe67e31c0b0343b09b0af5a3fd396a7d33eb

test:
  secret_key_base: 8c31decfc1bd3e2dc6bfcbb569a42419bd809e5de3cf344c306f2ea855b88da38f041208fdc0dce038c3acd9a9199da4d886cbdf79b3e5b666083ef31c1f11cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
