# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create( name: 'Star Wars' }, { name: 'Lord of the Rings' )
#   Character.create(name: 'Luke', movie: movies.first)

Category.create(name: 'Lighting')
Category.create(name: 'Entertainment')
Category.create(name: 'Climate')
Category.create(name: 'Security')
Category.create(name: 'Safety')
Category.create(name: 'Family')
Category.create(name: 'Outdoors')
Category.create(name: 'Assistive')

Feature.create(description: "I want my lights to change colors when I play music.")                         #1
Feature.create(description: "I want my lights to turn off automatically when I'm not in the room.")         #2
Feature.create(description: "I want my lights to adjust themselves automatically for my needs.")            #3
Feature.create(description: "I want to see my house live on my cellphone.")                                 #4
Feature.create(description: "I want to keep digital recordings of my house's surroundings.")                #5
Feature.create(description: "I want to lock/unlock my door from anywhere.")                                 #6
Feature.create(description: "I want to see who is at the door from anywhere.")                              #7
Feature.create(description: "I want to stream music throughout my house.")                                  #8
Feature.create(description: "I want to control all of my devices with a single remote.")                    #9
Feature.create(description: "I want to connect all of my media players to a single device.")                #10
Feature.create(description: "I want to access all my entertainment services through a single interface.")   #11
Feature.create(description: "I want to voice control my music and shows.")                                  #12
Feature.create(description: "I want to see and speak with my family and friends from anywhere in the home.")             #13
Feature.create(description: "I want to control my house using voice commands.")                             #14
Feature.create(description: "I want my thermostat to adjust itself.")                                       #15
Feature.create(description: "I want to know when there is someone at the door, even if I can't hear them.") #16
Feature.create(description: "I want to know about water leaks as soon as they happen, even when I'm not home.")                                                                                                     #17
Feature.create(description: "I want to moniter and control small appliances remotely.")                      #18
Feature.create(description: "I want my water valve to shut off if it detects a leak.")                      #19
Feature.create(description: "I want a thermostat that learns my habits.")                                   #20
Feature.create(description: "I want to regulate energy usage to save money and the environment.")           #21
Feature.create(description: "I want my fan to turn on only when it gets too hot.")                      #22
Feature.create(description: "I want to listen to music while I take a shower.")                  #23
Feature.create(description: "I want sprinklers that work automatically.")                                   #24
Feature.create(description: "I want sprinklers that won't turn on if it's going to rain.")                  #25
Feature.create(description: "I want a lawn that mows itself.")                                              #26
Feature.create(description: "I want to know if the plants in my flowerbed/garden are healthy.")             #27
Feature.create(description: "I want to listen to my music outdoors.")                                       #28
Feature.create(description: "I want to play music in several rooms of my home.")                            #29
Feature.create(description: "I want to check in on my kid(s) when I'm not home.")                           #30
Feature.create(description: "I want to check in on my pet(s) when I'm not home.")                           #31
Feature.create(description: "I want to know that my kids are safe when they aren't home.")                  #32
Feature.create(description: "I want to feed my pets remotely.")                                             #33
Feature.create(description: "I want to be alerted if there is a gas leak in my home.")                      #34
Feature.create(description: "I want a home security system that can send alerts directly to my phone.")                      #35

CategoryFeature.create(category_id: 1, feature_id: 1)
CategoryFeature.create(category_id: 1, feature_id: 2)
CategoryFeature.create(category_id: 1, feature_id: 3)
CategoryFeature.create(category_id: 1, feature_id: 20)
CategoryFeature.create(category_id: 2, feature_id: 1)
CategoryFeature.create(category_id: 2, feature_id: 8)
CategoryFeature.create(category_id: 2, feature_id: 9)
CategoryFeature.create(category_id: 2, feature_id: 10)
CategoryFeature.create(category_id: 2, feature_id: 11)
CategoryFeature.create(category_id: 2, feature_id: 12)
CategoryFeature.create(category_id: 2, feature_id: 23)
CategoryFeature.create(category_id: 2, feature_id: 27)
CategoryFeature.create(category_id: 2, feature_id: 28)
CategoryFeature.create(category_id: 3, feature_id: 9)
CategoryFeature.create(category_id: 3, feature_id: 14)
CategoryFeature.create(category_id: 3, feature_id: 19)
CategoryFeature.create(category_id: 3, feature_id: 20)
CategoryFeature.create(category_id: 3, feature_id: 21)
CategoryFeature.create(category_id: 3, feature_id: 22)
CategoryFeature.create(category_id: 4, feature_id: 4)
CategoryFeature.create(category_id: 4, feature_id: 5)
CategoryFeature.create(category_id: 4, feature_id: 6)
CategoryFeature.create(category_id: 4, feature_id: 7)
CategoryFeature.create(category_id: 4, feature_id: 8)
CategoryFeature.create(category_id: 4, feature_id: 15)
CategoryFeature.create(category_id: 4, feature_id: 29)
CategoryFeature.create(category_id: 4, feature_id: 30)
CategoryFeature.create(category_id: 4, feature_id: 31)
CategoryFeature.create(category_id: 5, feature_id: 4)
CategoryFeature.create(category_id: 5, feature_id: 9)
CategoryFeature.create(category_id: 5, feature_id: 13)
CategoryFeature.create(category_id: 5, feature_id: 16)
CategoryFeature.create(category_id: 5, feature_id: 17)
CategoryFeature.create(category_id: 5, feature_id: 18)
CategoryFeature.create(category_id: 5, feature_id: 29)
CategoryFeature.create(category_id: 5, feature_id: 30)
CategoryFeature.create(category_id: 5, feature_id: 31)
CategoryFeature.create(category_id: 5, feature_id: 33)
CategoryFeature.create(category_id: 6, feature_id: 4)
CategoryFeature.create(category_id: 6, feature_id: 5)
CategoryFeature.create(category_id: 6, feature_id: 6)
CategoryFeature.create(category_id: 6, feature_id: 7)
CategoryFeature.create(category_id: 6, feature_id: 13)
CategoryFeature.create(category_id: 6, feature_id: 28)
CategoryFeature.create(category_id: 6, feature_id: 29)
CategoryFeature.create(category_id: 6, feature_id: 30)
CategoryFeature.create(category_id: 6, feature_id: 31)
CategoryFeature.create(category_id: 6, feature_id: 32)
CategoryFeature.create(category_id: 7, feature_id: 15)
CategoryFeature.create(category_id: 7, feature_id: 24)
CategoryFeature.create(category_id: 7, feature_id: 25)
CategoryFeature.create(category_id: 7, feature_id: 26)
CategoryFeature.create(category_id: 7, feature_id: 27)
CategoryFeature.create(category_id: 8, feature_id: 2)
CategoryFeature.create(category_id: 8, feature_id: 3)
CategoryFeature.create(category_id: 8, feature_id: 5)
CategoryFeature.create(category_id: 8, feature_id: 6)
CategoryFeature.create(category_id: 8, feature_id: 7)
CategoryFeature.create(category_id: 8, feature_id: 12)
CategoryFeature.create(category_id: 8, feature_id: 13)
CategoryFeature.create(category_id: 8, feature_id: 15)

Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01KJYSO68&asins=B01KJYSO68&linkId=9319c8f319461cefce98482b999940de&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01KJYSO68/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01KJYSO68&linkCode=as2&tag=hassurunous-20&linkId=8ce4e9e9964bfd6c99274afff3da09ed">Philips 464495 Hue White and Color Ambiance A19 Starter Kit, 3rd Generation with Richer Colors, Works with Amazon Alexa</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01KJYSO68" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01KJYSO68/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01KJYSO68&linkCode=as2&tag=hassurunous-20&linkId=03d024a26ba09dab59d18aa2d4bcf52a"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01KJYSO68&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01KJYSO68" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: "Philips 464495 Hue White and Color Ambiance A19 Starter Kit, 3rd Generation with Richer Colors, Works with Amazon Alexa")
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01M9AU8MB&asins=B01M9AU8MB&linkId=b76368d574ab3fbcf12325cc15088797&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01M9AU8MB/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01M9AU8MB&linkCode=as2&tag=hassurunous-20&linkId=02189854401e7d212af1f44b3cf0e6bf">Philips - Hue White and Color Ambiance A19 Smart LED Light Bulb - Multicolor, 3rd Generation</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01M9AU8MB" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01M9AU8MB/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01M9AU8MB&linkCode=as2&tag=hassurunous-20&linkId=d6f430c1af58a10c8c46c964fb2c06bc"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01M9AU8MB&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01M9AU8MB" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Philips - Hue White and Color Ambiance A19 Smart LED Light Bulb - Multicolor, 3rd Generation')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B014H2OZAC&asins=B014H2OZAC&linkId=67c2dc884b9ac383351b34c8c5fe1dde&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B014H2OZAC/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B014H2OZAC&linkCode=as2&tag=hassurunous-20&linkId=eeef77754c315f655bb71bb18113186c">Philips Hue White A19 Starter Kit with two A19 LED light bulbs and bridge (hub), Works with Alexa</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B014H2OZAC" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B014H2OZAC/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B014H2OZAC&linkCode=as2&tag=hassurunous-20&linkId=7d412c0ecb0fd7b4bb031bc0ec03ae17"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B014H2OZAC&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B014H2OZAC" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Philips Hue White A19 Starter Kit with two A19 LED light bulbs and bridge (hub), Works with Alexa')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01ESW34RQ&asins=B01ESW34RQ&linkId=56e9e5a4f75098cbda2bf321dc82a4a9&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01ESW34RQ/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01ESW34RQ&linkCode=as2&tag=hassurunous-20&linkId=7032a0effbd9021e03fedb012c9f07bb">Philips 461020 Hue White Ambiance Single A19 Bulb, Works with Amazon Alexa</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01ESW34RQ" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01ESW34RQ/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01ESW34RQ&linkCode=as2&tag=hassurunous-20&linkId=3208294786e271865af71ccbb3e91463"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01ESW34RQ&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01ESW34RQ" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Philips 461020 Hue White Ambiance Single A19 Bulb, Works with Amazon Alexa')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01KJYSOGI&asins=B01KJYSOGI&linkId=0673132c8c04380dd0432ea372217320&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01KJYSOGI/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01KJYSOGI&linkCode=as2&tag=hassurunous-20&linkId=0508013579157e7459fc9ef9281f8da3">Philips 464602 Hue Motion Sensor</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01KJYSOGI" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01KJYSOGI/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01KJYSOGI&linkCode=as2&tag=hassurunous-20&linkId=e89e7e1ba7fc6ac82ceb0952118b7e81"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01KJYSOGI&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01KJYSOGI" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Philips 464602 Hue Motion Sensor')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00WBJGUA2&asins=B00WBJGUA2&linkId=75dfd0b53e149f2a9ed002b5ec86c977&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00WBJGUA2/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00WBJGUA2&linkCode=as2&tag=hassurunous-20&linkId=1d73a8e15921bf70871d512736ce1c67">Nest Cam Indoor security camera</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00WBJGUA2" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00WBJGUA2/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00WBJGUA2&linkCode=as2&tag=hassurunous-20&linkId=ab0b5fba96871262f2a7d9f352675941"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00WBJGUA2&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00WBJGUA2" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Nest Cam Indoor security camera')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00M5BX5P4&asins=B00M5BX5P4&linkId=c46c3574956b4b9e295a68cd103410b9&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00M5BX5P4/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00M5BX5P4&linkCode=as2&tag=hassurunous-20&linkId=a95080438243cda3755f7160c9d722d4">D-Link Pan &amp; Tilt Wi-Fi Camera (DCS-5009L)</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00M5BX5P4" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00M5BX5P4/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00M5BX5P4&linkCode=as2&tag=hassurunous-20&linkId=f61c7ac09a46d9afe565a687ab525e39"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00M5BX5P4&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00M5BX5P4" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'D-Link Pan & Tilt Wi-Fi Camera (DCS-5009L)')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00F0R9V76&asins=B00F0R9V76&linkId=4db300249ac30e9c49bd4cd11e11c19c&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00F0R9V76/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00F0R9V76&linkCode=as2&tag=hassurunous-20&linkId=2db4c4fe1acf8c71f68938b20059d49a">D-Link Camera Video Recorder mydlink-Enabled (DNR-202L)</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00F0R9V76" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00F0R9V76/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00F0R9V76&linkCode=as2&tag=hassurunous-20&linkId=bb299fc94a84c95daf033aab5f1edd78"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00F0R9V76&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00F0R9V76" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'D-Link Camera Video Recorder mydlink-Enabled (DNR-202L)')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B004P8K24W&asins=B004P8K24W&linkId=3bca86489d239ec7f26aaef92ff2fa18&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B004P8K24W/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B004P8K24W&linkCode=as2&tag=hassurunous-20&linkId=0af4861557bdbbdded0a56b38ff1cd78">D-Link Day &amp; Night Wi-Fi Camera with Remote Viewing (DCS-932L)</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B004P8K24W" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B004P8K24W/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B004P8K24W&linkCode=as2&tag=hassurunous-20&linkId=b11cb2e39fda4cdf30bc4c7d943bb476"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B004P8K24W&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B004P8K24W" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'D-Link Day & Night Wi-Fi Camera with Remote Viewing (DCS-932L)')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B0168IXO3M&asins=B0168IXO3M&linkId=3fc0e3e462fc2b0e60d567bf327a2479&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B0168IXO3M/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B0168IXO3M&linkCode=as2&tag=hassurunous-20&linkId=7307691c3d0bb174e740829e0fbf04ad">August Smart Lock - Latest Generation  (Silver)</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B0168IXO3M" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B0168IXO3M/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B0168IXO3M&linkCode=as2&tag=hassurunous-20&linkId=b212adf50b5766a96486d0d13e2107fe"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B0168IXO3M&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B0168IXO3M" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'August Smart Lock - Latest Generation (Silver)')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B010NZV14U&asins=B010NZV14U&linkId=d76d28c2716d6ed511677d5af294f030&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B010NZV14U/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B010NZV14U&linkCode=as2&tag=hassurunous-20&linkId=821dfa6bbd089576eedc354ff0c9d3ad">Samsung SmartThings Home Monitoring Kit</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B010NZV14U" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B010NZV14U/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B010NZV14U&linkCode=as2&tag=hassurunous-20&linkId=b061b8406645059e0e56881e1d7db16e"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B010NZV14U&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B010NZV14U" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Samsung SmartThings Home Monitoring Kit')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00N2ZDXW2&asins=B00N2ZDXW2&linkId=714da57cc4c0d9227d799e76c5c500bb&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00N2ZDXW2/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00N2ZDXW2&linkCode=as2&tag=hassurunous-20&linkId=d74c4a8c25be6b042877967089d9c358">Ring Wi-Fi Enabled Video Doorbell</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00N2ZDXW2" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00N2ZDXW2/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00N2ZDXW2&linkCode=as2&tag=hassurunous-20&linkId=7e0de5547bed234b7328f7dd23519ce2"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00N2ZDXW2&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00N2ZDXW2" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Ring Wi-Fi Enabled Video Doorbell')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01KZRPNIQ&asins=B01KZRPNIQ&linkId=a99ccdd2f280c94bb748c318cb107d3a&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01KZRPNIQ/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01KZRPNIQ&linkCode=as2&tag=hassurunous-20&linkId=97779f54e3a42de3abe7e3fdd9bb85d8">Denon AVRX4300H 9.2 Channel Full 4K Ultra HD AV Receiver with Built-in HEOS wireless technology featuring Bluetooth and Wi-Fi</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01KZRPNIQ" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01KZRPNIQ/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01KZRPNIQ&linkCode=as2&tag=hassurunous-20&linkId=d68be0bf398f317eb683816cc4dcac4a"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01KZRPNIQ&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01KZRPNIQ" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Denon AVR-X4300H 9.2 Channel Full 4K Ultra HD AV Receiver with Built-in HEOS wireless technology featuring Bluetooth and Wi-Fi')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00NZ80B80&asins=B00NZ80B80&linkId=637a1a69ddaea66dd4116d687d29eda3&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00NZ80B80/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00NZ80B80&linkCode=as2&tag=hassurunous-20&linkId=33322e24e2fb0af84eb3989f08bdf1dc">SONOS BOOST for Sonos Wireless Network</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00NZ80B80" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00NZ80B80/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00NZ80B80&linkCode=as2&tag=hassurunous-20&linkId=ad8a7fff4af3c16240c82a76cff4669c"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00NZ80B80&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00NZ80B80" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'SONOS BOOST for Sonos Wireless Network')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00EWCUK1Q&asins=B00EWCUK1Q&linkId=19fbe5d8086e5bf5e3338eb5d08f4e9c&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00EWCUK1Q/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00EWCUK1Q&linkCode=as2&tag=hassurunous-20&linkId=d06f557a1ebbfab0875cfa67259f1fde">Sonos PLAY:1 Compact Wireless Smart  Speaker for Streaming Music (Black)</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00EWCUK1Q" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00EWCUK1Q/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00EWCUK1Q&linkCode=as2&tag=hassurunous-20&linkId=a8c1d73b61b9d11fe011f30e749b5ca2"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00EWCUK1Q&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00EWCUK1Q" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Sonos PLAY:1 Compact Wireless Smart Speaker for Streaming Music')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00ZV9RDKK&asins=B00ZV9RDKK&linkId=a192882499c73b53cf9d8817a9f99a89&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00ZV9RDKK/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00ZV9RDKK&linkCode=as2&tag=hassurunous-20&linkId=571993c78f46d48a750ba541334ff6f2">All-New Fire TV Stick with Alexa Voice Remote | Streaming Media Player</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00ZV9RDKK" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00ZV9RDKK/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00ZV9RDKK&linkCode=as2&tag=hassurunous-20&linkId=2edc111805d40ac79c9cd741317e5eda"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00ZV9RDKK&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00ZV9RDKK" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'All-New Fire TV Stick with Alexa Voice Remote | Streaming Media Player')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B014PDFP9S&asins=B014PDFP9S&linkId=48b5f5678bbcb844f238b618b9942c56&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00N3RFCBE/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00N3RFCBE&linkCode=as2&tag=hassurunous-20&linkId=171ee947bb7064d3d2bce988c311ccdb">Logitech Harmony Ultimate Home Touch Screen Programmable Remote for 15 Home Entertainment and Automation Devices (black)</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00N3RFCBE" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00N3RFCBE/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00N3RFCBE&linkCode=as2&tag=hassurunous-20&linkId=29ed12827e7941a509da717570db1576"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00N3RFCBE&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00N3RFCBE" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Logitech Harmony Ultimate Home Touch Screen Programmable Remote for 15 Home Entertainment and Automation Devices (black)')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01ENWYKRE&asins=B01ENWYKRE&linkId=37809951ced3483b330693999777ee6f&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01ENWYKRE/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01ENWYKRE&linkCode=as2&tag=hassurunous-20&linkId=1c19163fc6dd3ba58699e8d1484b071b">Nucleus Anywhere Intercom with Amazon Alexa, 2 Pack</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01ENWYKRE" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01ENWYKRE/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01ENWYKRE&linkCode=as2&tag=hassurunous-20&linkId=6f61339cb9da98013866dfca9d865df6"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01ENWYKRE&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01ENWYKRE" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Nucleus Anywhere Intercom with Amazon Alexa, 2 Pack')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01MA4IOQK&asins=B01MA4IOQK&linkId=540a56df9fb873d11bafcbaf003aac18&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01ENWYKRE/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01ENWYKRE&linkCode=as2&tag=hassurunous-20&linkId=474a896641ba4cf2d5ed4b4a1842cfb4">Nucleus Anywhere Intercom with Amazon Alexa, 2 Pack</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01ENWYKRE" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01ENWYKRE/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01ENWYKRE&linkCode=as2&tag=hassurunous-20&linkId=17ea6ed8a32b88dcdea76780a2f44578"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01ENWYKRE&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01ENWYKRE" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'iMCO CoWatch with Amazon Alexa, Silver')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00X4WHP5E&asins=B00X4WHP5E&linkId=1f2d19bcb1b7a194a2d95c190001745f&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00X4WHP5E/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00X4WHP5E&linkCode=as2&tag=hassurunous-20&linkId=7c8bbb58915e1c2b849634db90839279">Amazon Echo - Black</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00X4WHP5E" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00X4WHP5E/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00X4WHP5E&linkCode=as2&tag=hassurunous-20&linkId=94b2e757a8bef52f2c6a632678b0e7e4"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00X4WHP5E&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00X4WHP5E" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Amazon Echo')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01DFKC2SO&asins=B01DFKC2SO&linkId=b8d2345d5d6fdcd279816f0f309b10c5&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01DFKC2SO/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01DFKC2SO&linkCode=as2&tag=hassurunous-20&linkId=69f9607a4c0e9614ab1941cb688837ea">All-New Echo Dot (2nd Generation) - Black</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01DFKC2SO" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01DFKC2SO/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01DFKC2SO&linkCode=as2&tag=hassurunous-20&linkId=fc61782c62a3702fdd14229268f846a0"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01DFKC2SO&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01DFKC2SO" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'All-New Echo Dot (2nd Generation)')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01LTHM8LG&asins=B01LTHM8LG&linkId=7a94501dd6532287ae4146d5b9bd5b4b&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01LTHM8LG/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01LTHM8LG&linkCode=as2&tag=hassurunous-20&linkId=1aa6e6618aa495abaf506c313107cfcf">Lyric T5 Wi-Fi Thermostat, Works with Apple HomeKit and Amazon Alexa</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01LTHM8LG" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01LTHM8LG/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01LTHM8LG&linkCode=as2&tag=hassurunous-20&linkId=ccf2bb0f777551b35cd38c7d9894858f"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01LTHM8LG&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01LTHM8LG" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Lyric T5 Wi-Fi Thermostat, Works with Apple HomeKit and Amazon Alexa')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00MOIYIN6&asins=B00MOIYIN6&linkId=be8dcdfc13139d41321d1fd8ef555191&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00MOIYIN6/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00MOIYIN6&linkCode=as2&tag=hassurunous-20&linkId=5a774e3f0ca26eee4fd7309b179aaf09">Samsung SmartThings Water Leak Sensor</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00MOIYIN6" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00MOIYIN6/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00MOIYIN6&linkCode=as2&tag=hassurunous-20&linkId=4cb0d28837eddc60b8cea0f1abc779f5"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00MOIYIN6&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00MOIYIN6" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Samsung SmartThings Water Leak Sensor')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B010NZV0GE&asins=B010NZV0GE&linkId=36e504e69e9d6863cf4ded3c5e5a7cfc&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B010NZV0GE/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B010NZV0GE&linkCode=as2&tag=hassurunous-20&linkId=51dccf980fb9a38e1b1d2f161c69bb63">Samsung SmartThings Hub- White</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B010NZV0GE" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B010NZV0GE/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B010NZV0GE&linkCode=as2&tag=hassurunous-20&linkId=afd0983c21f4ad8fca86c7d40d5a9b2a"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B010NZV0GE&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B010NZV0GE" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Samsung SmartThings Hub - White')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01LE9OD3A&asins=B01LE9OD3A&linkId=d3d3ecc922aacde6312a5da171b9ba19&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01LE9OD3A/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01LE9OD3A&linkCode=as2&tag=hassurunous-20&linkId=16f82476eb9f8cfc1cce052141fd0252">Z-Wave 3/4" Valve Water Control Valve by Leak Gopher, Z-Wave Plus, NSF Certified, USA MADE</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01LE9OD3A" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01LE9OD3A/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01LE9OD3A&linkCode=as2&tag=hassurunous-20&linkId=d9e297016c31147c69ddc653840566e5"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01LE9OD3A&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01LE9OD3A" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Z-Wave 3/4" Valve Water Control Valve by Leak Gopher, Z-Wave Plus, NSF Certified, USA MADE')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00MI5V5N6&asins=B00MI5V5N6&linkId=7947954d63647416273e9669824e6bbc&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00MI5V5N6/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00MI5V5N6&linkCode=as2&tag=hassurunous-20&linkId=c12689838e75d787d03c08f7e2372477">Samsung SmartThings Outlet, Works with Amazon Alexa</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00MI5V5N6" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00MI5V5N6/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00MI5V5N6&linkCode=as2&tag=hassurunous-20&linkId=41a576e346d5082fd3bbbe6785aea50a"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00MI5V5N6&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00MI5V5N6" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Samsung SmartThings Outlet, Works with Amazon Alexa')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B0131RG6VK&asins=B0131RG6VK&linkId=d897866faea9fc5b7f08f44a8a69b2b1&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B0131RG6VK/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B0131RG6VK&linkCode=as2&tag=hassurunous-20&linkId=bf2abc03e6b45196d39ba70416dd666c">Nest Learning Thermostat, 3rd Generation, Works with Amazon Alexa</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B0131RG6VK" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B0131RG6VK/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B0131RG6VK&linkCode=as2&tag=hassurunous-20&linkId=7dd69c0f08139de941267d316b27690b"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B0131RG6VK&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B0131RG6VK" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Nest Learning Thermostat, 3rd Generation, Works with Amazon Alexa')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00XD8WZX6&asins=B00XD8WZX6&linkId=aebb6fd7c78b6bd8e0081d89380f5e2e&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', image_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00XD8WZX6/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00XD8WZX6&linkCode=as2&tag=hassurunous-20&linkId=fc64b4e063648832ab17531562dde31d">Aeotec by Aeon Labs ZW095 Home Energy Meter, Small, White</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00XD8WZX6" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', text_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00XD8WZX6/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00XD8WZX6&linkCode=as2&tag=hassurunous-20&linkId=28d37f02212a8347e5f2096b6793bc9f"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00XD8WZX6&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00XD8WZX6" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Aeotec by Aeon Labs ZW095 Home Energy Meter')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B001EDVU6K&asins=B001EDVU6K&linkId=aaa9ee7518f81bb855664027faf7c42c&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B001EDVU6K/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B001EDVU6K&linkCode=as2&tag=hassurunous-20&linkId=f6685417bed92975673c77fea0d49745">Vornado TVH600 Whole Room Vortex Heater, Automatic Climate Control</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B001EDVU6K" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B001EDVU6K/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B001EDVU6K&linkCode=as2&tag=hassurunous-20&linkId=3bfa935f7567cba0d0d001c6293d709c"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B001EDVU6K&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B001EDVU6K" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Vornado TVH600 Whole Room Vortex Heater, Automatic Climate Control')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00J4QTSB8&asins=B00J4QTSB8&linkId=12bb7b5cf2adf3977414ed24f4c0ae34&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00J4QTSB8/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00J4QTSB8&linkCode=as2&tag=hassurunous-20&linkId=9a741beeb3c19befef55bd818887597d">H2oVibe Rain Showerhead Jet with Wireless Bluetooth Speaker - Polished Chrome</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00J4QTSB8" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00J4QTSB8/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00J4QTSB8&linkCode=as2&tag=hassurunous-20&linkId=9cbefbef4d5c845e5ec92a7011204f5e"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00J4QTSB8&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00J4QTSB8" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" H2oVibe Rain Showerhead Jet with Wireless Bluetooth SpeakerLifesmart Large Room 6 Element Infrared Heater w/Remote', name: 'H2oVibe Rain Showerhead Jet with Wireless Bluetooth Speaker')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01D1NMLJU&asins=B01D1NMLJU&linkId=d0170003671fda9c45ed083b45e913b0&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01D1NMLJU/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01D1NMLJU&linkCode=as2&tag=hassurunous-20&linkId=6572a3d097a0623347fd317bae748d46">Rachio Smart Sprinkler Controller, 8 Zone 2nd Generation, Works with Alexa</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01D1NMLJU" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01D1NMLJU/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01D1NMLJU&linkCode=as2&tag=hassurunous-20&linkId=1fa6698b40583ba765601e8448bdbbe9"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01D1NMLJU&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01D1NMLJU" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Rachio Smart Sprinkler Controller, 8 Zone 2nd Generation, Works with Alexa')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00SJEUFF4&asins=B00SJEUFF4&linkId=bbce53e69fec826c4fe4d0736b2baba6&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00SJEUFF4/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00SJEUFF4&linkCode=as2&tag=hassurunous-20&linkId=99652351149c387e199f7f49c56ab060">WORX Landroid Robotic Lawn Mower, 28-volt WG794</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00SJEUFF4" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00SJEUFF4/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00SJEUFF4&linkCode=as2&tag=hassurunous-20&linkId=2394e8bad324825de7d51ea55c38ad92"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00SJEUFF4&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00SJEUFF4" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'WORX Landroid Robotic Lawn Mower, 28-volt WG794')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01FQEMGJM&asins=B01FQEMGJM&linkId=c60e2aea7242d88e603b71d2fccfd4a4&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01FQEMGJM/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01FQEMGJM&linkCode=as2&tag=hassurunous-20&linkId=c1419779cd455110c6819995b5e6f69e">Edyn Garden Sensor</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01FQEMGJM" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01FQEMGJM/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01FQEMGJM&linkCode=as2&tag=hassurunous-20&linkId=318d52ee22b39f4b48f3aed0a056fa02"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01FQEMGJM&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01FQEMGJM" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Edyn Garden Sensor')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B017WL4N84&asins=B017WL4N84&linkId=cc08e87a601d2219387bfd01575c03de&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B017WL4N84/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B017WL4N84&linkCode=as2&tag=hassurunous-20&linkId=02d3a5afe0d51de85173a4562bded796">Invoxia Smart Portable Speaker with Amazon Alexa, Blue</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B017WL4N84" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B017WL4N84/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B017WL4N84&linkCode=as2&tag=hassurunous-20&linkId=612b60ef844f1467ce4782cbea4ae284"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B017WL4N84&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B017WL4N84" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Invoxia Smart Portable Speaker with Amazon Alexa, Blue')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B0155N973M&asins=B0155N973M&linkId=7672edba5b8da3002112f7e6233d6f64&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B0155N973M/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B0155N973M&linkCode=as2&tag=hassurunous-20&linkId=70eb12ed4d45b6baa149946b13d7bf61">Bose SoundTouch 10 Wireless Music System Bundle 2-Pack - Black</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B0155N973M" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B0155N973M/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B0155N973M&linkCode=as2&tag=hassurunous-20&linkId=19181ea07b48f441365555b2aa030c90"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B0155N973M&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B0155N973M" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Bose SoundTouch 10 Wireless Music System Bundle 2-Pack - Black')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00JGWN8O8&asins=B00JGWN8O8&linkId=a7b64593018052e321dd58b18ae4d143&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00JGWN8O8/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00JGWN8O8&linkCode=as2&tag=hassurunous-20&linkId=4d088d2cb17a51deba49fe73662e17df">Petcube Camera | 720p Video, 2-Way Audio, and Built-in Laser Toy</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00JGWN8O8" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00JGWN8O8/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00JGWN8O8&linkCode=as2&tag=hassurunous-20&linkId=d9e794553410f04f0edb21253656ef0d"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00JGWN8O8&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00JGWN8O8" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Petcube Camera | 720p Video, 2-Way Audio, and Built-in Laser Toy')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01N63MFAB&asins=B01N63MFAB&linkId=9a31080d9f54b22173c388e8545ffdd4&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01N63MFAB/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01N63MFAB&linkCode=as2&tag=hassurunous-20&linkId=e4cdde9d9800cedef51ed3f02eb23064">MX-LOCare Mobile Personal Emergency Response GPS Watch Wifi Tracking Safety SmartWatch Tracker for Elderly, Kids, Teens, Autism, Alzheimer</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01N63MFAB" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01N63MFAB/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01N63MFAB&linkCode=as2&tag=hassurunous-20&linkId=922fedcc579ea626bc88a7111f1d1a6e"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01N63MFAB&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01N63MFAB" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'MX-LOCare Mobile Personal Emergency Response GPS Watch Wifi Tracking Safety SmartWatch Tracker for Elderly, Kids, Teens, Autism, Alzheimer')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01M7UMW0O&asins=B01M7UMW0O&linkId=a70b059e757e1f8da895712db681a314&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01M7UMW0O/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01M7UMW0O&linkCode=as2&tag=hassurunous-20&linkId=e75b7ce3699f5661a4193bb590a6faf6">Smart Pet Feeder, Automatic Pet Feeder for Dogs and Cats, Built in 1 Million Pixels Webcam&amp;Wi-Fi, 4.3L Food Tank, Compatible with iOS/Android or Other Smart Devices,App Feeder-L11.8xW9.6xH14.9in</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01M7UMW0O" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01M7UMW0O/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01M7UMW0O&linkCode=as2&tag=hassurunous-20&linkId=671b24d8fe19078707ed2569fbf5cb42"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01M7UMW0O&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01M7UMW0O" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Smart Pet Feeder, Automatic Pet Feeder for Dogs and Cats, Built in 1 Million Pixels Webcam & Wi-Fi, 4.3L Food Tank, Compatible with iOS/Android or Other Smart Devices, App Feeder-L11.8xW9.6xH14.9in')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00XV1RD0K&asins=B00XV1RD0K&linkId=a7a2b4c977c1576d8a558f3e9d71cfeb&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00XV1RD0K/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00XV1RD0K&linkCode=as2&tag=hassurunous-20&linkId=1145056704217b6d7764fbd92fa6e380">Nest Protect smoke &amp; carbon monoxide alarm, Wired (2nd gen)</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00XV1RD0K" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00XV1RD0K/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00XV1RD0K&linkCode=as2&tag=hassurunous-20&linkId=0012dc35cd9a6cff2dcf799855165f18"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00XV1RD0K&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00XV1RD0K" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Nest Protect smoke & carbon monoxide alarm, (2nd gen)')

############## In Progress Below ##############

# Product.create(frame_link: '', text_link: '', image_link: '', name: '')
#
# Feature.create(description: "I want a heater that turns itself on when it gets too cold.")                  #23
# Feature.create(description: "I want sprinklers that work automatically.")                                   #24
# Feature.create(description: "I want sprinklers that won't turn on if it's going to rain.")                  #25
# Feature.create(description: "I want a lawn that mows itself.")                                              #26
# Feature.create(description: "I want to know if the plants in my flowerbed/garden are healthy.")             #27
# Feature.create(description: "I want to listen to my music outdoors.")                                       #28
# Feature.create(description: "I want to play music in several rooms of my home.")                            #29
# Feature.create(description: "I want to check in on my kid(s) when I'm not home.")                           #30
# Feature.create(description: "I want to check in on my pet(s) when I'm not home.")                           #31
# Feature.create(description: "I want to know that my kids are safe when they aren't home.")                  #32
# Feature.create(description: "I want to feed my pets remotely.")                                             #33
# Feature.create(description: "I want to be alerted if there is a gas leak in my home.")                      #34
#
FeatureProduct.create(feature_id: 1, product_id: 1, additional_info: "This kit includes the Hue Bridge and 3 of their newest generation of full-color Hue Bulbs for the best colors and control of your lighting. In order to sync with your music, you'll need to download an application to connect the music and lights. We recommend Ambify. (Note: If you only need the 3 bulbs in this package, you can ignore the bulb listing!)")
FeatureProduct.create(feature_id: 1, product_id: 2, additional_info: "The more Hue Bulbs, the more you can mix things up! Each Hue Bridge can support up to 50 bulbs!")
FeatureProduct.create(feature_id: 2, product_id: 3, additional_info: "This kit includes the Hue Bridge and 3 of their newest generation of white Hue Bulbs for the best control of your lighting. (Note: If you only need the 3 bulbs in this package, you can ignore the bulb listing!)")
FeatureProduct.create(feature_id: 2, product_id: 4, additional_info: "The more Hue Bulbs, the more you can mix things up! Each Hue Bridge can support up to 50 bulbs!")
FeatureProduct.create(feature_id: 2, product_id: 5, additional_info: "Place the motion sensors wherever you want to control your Hue lights. The simple Hue app will allow you to connect lights to the motion sensors however you like!")
FeatureProduct.create(feature_id: 3, product_id: 1, additional_info: "This kit includes the Hue Bridge and 3 of their newest generation of full-color Hue Bulbs for the best colors and control of your lighting. Sunn is a great app that lowers the harshness of your lights to match the time of day to help protect your circadian rhythm and make it easier to get your beauty sleep! (Note: If you only need the 3 bulbs in this package, you can ignore the bulb listing!)")
FeatureProduct.create(feature_id: 3, product_id: 2, additional_info: "The more Hue full-color Bulbs, the more you can mix things up! Each Hue Bridge can support up to 50 bulbs!")
FeatureProduct.create(feature_id: 3, product_id: 3, additional_info: "This kit includes the Hue Bridge and 3 of their newest generation of white Hue Bulbs for the best control of your lighting. Sunn is a great app that lowers the harshness of your lights to match the time of day to help protect your circadian rhythm and make it easier to get your beauty sleep! (Note: If you only need the 3 bulbs in this package, you can ignore the bulb listing!)")
FeatureProduct.create(feature_id: 3, product_id: 4, additional_info: "The more Hue Bulbs, the more you can mix things up! Each Hue Bridge can support up to 50 bulbs!")
FeatureProduct.create(feature_id: 4, product_id: 6, additional_info: "Nest offers one of the easiest set ups in the security camera market. You can view a live feed of the camera(s) from your phone, tablet, or computer and even record video for later review. Also available is a discounted pack of 3 cameras or a combination of 1 indoor and 1 outdoor camera, to give you an even greater sense of safety and security, from anywhere in the world.")
FeatureProduct.create(feature_id: 4, product_id: 7, additional_info: "The D-Link Pan and Tilt camera is another great option, which allows you to move the camera around from your phone, tablet, or computer to provide a more dynamic viewing area. ")
FeatureProduct.create(feature_id: 4, product_id: 8, additional_info: "The D-Link Video Recorder will allow you to store the video from your D-Link camera safely in your home rather than on the cloud, so that you can be sure your security is private.")
FeatureProduct.create(feature_id: 5, product_id: 6, additional_info: "Nest offers one of the easiest set ups in the security camera market. You can view a live feed of the camera(s) from your phone, tablet, or computer and even store video online for later review, for a small fee. Also available is a discounted pack of 3 cameras or a combination of 1 indoor and 1 outdoor camera, to give you an even greater sense of safety and security, from anywhere in the world.")
FeatureProduct.create(feature_id: 5, product_id: 7, additional_info: "The D-Link Pan and Tilt camera is another great option, which allows you to move the camera around from your phone, tablet, or computer to provide a more dynamic viewing area. ")
FeatureProduct.create(feature_id: 5, product_id: 9, additional_info: "The D-Link Day and Night Wifi camera is another great option for home security. With the same remote viewing capabilities of the Nest or other D-Link cameras, this camera is simple to install and set up. ")
FeatureProduct.create(feature_id: 5, product_id: 8, additional_info: "The D-Link Video Recorder will allow you to store the video from your D-Link camera safely in your home rather than on the cloud, so that you can be sure your security is private.")
FeatureProduct.create(feature_id: 6, product_id: 10, additional_info: "August smart locks are a great investment for controlling the access to your home. With a fully functional mobile application and support with systems such as SmartThings, the August locks allow you to control your door locks from anywhere in the world. Never forget to lock the door again, and never worry if your kids forget their keys.")
FeatureProduct.create(feature_id: 36, product_id: 11, additional_info: "The SmartThings Home Monitoring kit is really an amazing introductory security setup for anyone interested in smart homes. In addition to the motion sensor and contact sensors, you also get a SmartThings Hub, which means you can add hundreds of devices to your system, including non-security items, without having to worry.")
FeatureProduct.create(feature_id: 7, product_id: 12, additional_info: "The Ring Video Doorbell is probably the most versatile smart doorbell on the market, especially for the price. With high quality audio and video transmission, not only can you ensure your home's safety, you can also ensure that no package goes undelivered, that the kids are home, and more.")
FeatureProduct.create(feature_id: 8, product_id: 15, additional_info: "The SONOS PLAY:1 speakers are great for easy distributed audio throughout the home. They link up to your WiFi and allow you to choose which speakers you would like to use. Higher versions (such as the PLAY:5) allow for higher sound quality.")
FeatureProduct.create(feature_id: 8, product_id: 14, additional_info: "For larger houses, or houses where the WiFi signal doesn't reach certain rooms you want to play music in, the SONOS BOOST allows you to connect the SONOS speakers to eachother, instead of directly to the WiFi network, meaning you can greatly extend their potential range.")
FeatureProduct.create(feature_id: 9, product_id: 17, additional_info: "The Logitech Harmony remotes are the undisputed champions of universal remotes, and this one includes a fully functional touch screen that allows you to use customized controls on up to 15 different devices. This model even features the ability to control home automation devices, such as the SmartThings Hub.")
FeatureProduct.create(feature_id: 10, product_id: 13, additional_info: "The Denon AVRX4300H is one of the best receivers on the market. It includes full Bluetooth and Wi-Fi capabilities, giving you the power to control all of your home theater equipment from your phone or other smart devices.")
FeatureProduct.create(feature_id: 11, product_id: 16, additional_info: "The new Amazon Fire Stick allows you to access a truly massive collection of tv shows, movies, and music. When it comes to all-in-one media devices, the Fire Stick is touch to beat.")
FeatureProduct.create(feature_id: 12, product_id: 16, additional_info: "The new Amazon Fire Stick allows you to access a truly massive collection of tv shows, movies, and music. When it comes to all-in-one media devices, the Fire Stick is touch to beat. Additionally, the new version comes with a voice control through the remote to make the use of the system that much easier and more accessible.")
FeatureProduct.create(feature_id: 13, product_id: 18, additional_info: "The Nucleus Anywhere Intercoms are a really great gift for family and friends alike. They allow for instantaneous voice and video communication from another Nucleus tablet or directly from your smart phone. Additionally, they include music, news, weather, and other capabilities, such as a Do Not Disturb mode which even allows you to shutter the camera.")
FeatureProduct.create(feature_id: 14, product_id: 20, additional_info: "The Amazon Echo is easily the best voice-controlled smart home controller on the market. The full Echo includes a powerful speaker system inside the tower and can respond to commands to control hundreds of devices. Once you have the Echo, you can control nearly any other device on this site with it.")
FeatureProduct.create(feature_id: 14, product_id: 21, additional_info: "The Amazon Echo Dot is very similar to the Amazon Echo. In order to reduce cost and size, Amazon essentially has just removed the speaker system that was built into the full-sized Echo. The Echo and the Echo Dots can communicate across the house as well, so feel free to place several dots around the home for maximum control!")
FeatureProduct.create(feature_id: 15, product_id: 22, additional_info: "The Honeywell Lyric T5 is the best smart thermostat for the money on the market right now. It is extremely easy to program and use, and it can be integrated with Siri, Amazon Alexa, and Apple HomeKit among other smart systems. One of the coolest features is the advanced geofencing, which can detect when you are on your way home if you have the app installed and can have the house the perfect temperature for you when you get there, without wasting energy all day to keep the temperature when nobody is home.")
FeatureProduct.create(feature_id: 15, product_id: 27, additional_info: "Easily the most well-known smart thermostat on the market, the Nest thermostat earns its reputation as the most reliable, most advanced smart thermostat out there. It's a bit more expensive than the Lyric T5, but it is extremely easy to use and has the best design of any thermostat on the market. It includes all of the features of the Lyric T5 and more, including an advanced AI that can learn your schedule and adjust your temperatures without making you set a schedule explicitly.")
FeatureProduct.create(feature_id: 16, product_id: 12, additional_info: "The Ring Wi-Fi Enabled Video Doorbell has the ability to interface with a ton of other devices to let you know that someone is at the door. It can detect motion, or when the doorbell is rung. For those hard of hearing, or just those listening to their music too loud, the Ring Doorbell, combined with the IFTTT app can flash your lights, pause your music, or alert you in another way so that you never miss that important delivery.")
FeatureProduct.create(feature_id: 16, product_id: 1, additional_info: "This Hue kit contains 3 full-color lights and can be integrated with the Ring Doorbell through the IFTTT app to blink the lights to let you know someone is at the door. You can even have it flash a specific color to distinguish between alerts. ")
FeatureProduct.create(feature_id: 16, product_id: 2, additional_info: "If needed, these are the Hue full-color bulbs to expand the Hue Bridge kits so you can control even more lights throughout the house.")
FeatureProduct.create(feature_id: 16, product_id: 3, additional_info: "This Hue Kit contains 3 white lights and can be integrated with the Ring Doorbell through the IFTTT app to blink the lights to let you know someone is at the door. ")
FeatureProduct.create(feature_id: 16, product_id: 4, additional_info: "If needed, these are the Hue white bulbs to expand the Hue Bridge kits so you can control even more lights throughout the house.")
FeatureProduct.create(feature_id: 17, product_id: 23, additional_info: "The Samsung SmartThings leak detection sensor can be placed anywhere through the home to alert you if there is water somewhere it shouldn't be. Place them near your washer, your water heater, that one leaky spot in the basement, or anywhere you want to monitor for water. In order to communicate with the sensor, you'll also need the SmartThings Hub, which allows you to expand and integrate more devices into your system as you desire.")
FeatureProduct.create(feature_id: 17, product_id: 24, additional_info: "The SmartThings Hub is the main brain of the SmartThings brand of smart home automation systems. It is extremely easy to set up, can send alerts directly to your phone, and is compatible with hudreds of devices, allowing you to grow your smart home at the pace most comfortable for you.")
FeatureProduct.create(feature_id: 18, product_id: 26, additional_info: "The SmartThings outlet allows you to control the power to lamps, small appliances, and other electronics. Use it to monitor the energy usage of your TV, control lamps in an office, or anything else you can think of. In order to communicate with the outlet, you'll also need the SmartThings Hub, which allows you to expand and integrate more devices into your system as you desire.")
FeatureProduct.create(feature_id: 18, product_id: 24, additional_info: "The SmartThings Hub is the main brain of the SmartThings brand of smart home automation systems. It is extremely easy to set up, can send alerts directly to your phone, and is compatible with hudreds of devices, allowing you to grow your smart home at the pace most comfortable for you.")
FeatureProduct.create(feature_id: 19, product_id: 25, additional_info: "The Leak Gopher Water Control Valve allows you to protect your home from unfortunate water leaks from burst pipes, busted appliances, or even the kids leaving a sink running. Combined with a Z-Wave smart hub, such as the SmartThings Hub, the Leak Gopher Water Control Valve can, for example, save you thousands of dollars in repairs by turning off the main water line to the house in the event a leak is detected on a SmartThings Water Leak Detector. Important Note!: Make sure you choose the right size for your home's main water line! If you aren't sure what size you need, consult a plumber to be sure.")
FeatureProduct.create(feature_id: 19, product_id: 23, additional_info: "The Samsung SmartThings leak detection sensor can be placed anywhere through the home to alert you if there is water somewhere it shouldn't be. Place them near your washer, your water heater, that one leaky spot in the basement, or anywhere you want to monitor for water. In order to communicate with the sensor, you'll also need the SmartThings Hub, which allows you to expand and integrate more devices into your system as you desire.")
FeatureProduct.create(feature_id: 19, product_id: 24, additional_info: "The SmartThings Hub is the main brain of the SmartThings brand of smart home automation systems. It is extremely easy to set up, can send alerts directly to your phone, and is compatible with hudreds of devices, allowing you to grow your smart home at the pace most comfortable for you.")
FeatureProduct.create(feature_id: 20, product_id: 27, additional_info: "Easily the most well-known smart thermostat on the market, the Nest thermostat earns its reputation as the most reliable, most advanced smart thermostat out there. It is extremely easy to use and has the best design of any thermostat on the market. It includes a wealth of amazing features, including an advanced AI that can learn your schedule and adjust your temperatures without making you set a schedule explicitly.")
FeatureProduct.create(feature_id: 21, product_id: 24, additional_info: "The SmartThings Hub is the main brain of the SmartThings brand of smart home automation systems. It is extremely easy to set up, can send alerts directly to your phone, and is compatible with hudreds of devices, allowing you to grow your smart home at the pace most comfortable for you. Every device listed here is supported by the Hub, so you can enjoy the easiest, most satisfying, greenest home on the block!")
FeatureProduct.create(feature_id: 21, product_id: 28, additional_info: "Aeon Labs' Home Energy meter connects safely and easily, directly to the main breaker box. This allows you to track the total energy usage of your entire home, so that you can be sure you are getting the maximum savings from your new smart home. Connect it to your SmartThings Hub to monitor and track energy usage in your home to reduce your carbon footprint (and your bills!).")
FeatureProduct.create(feature_id: 21, product_id: 26, additional_info: "The SmartThings outlet allows you to control the power to lamps, small appliances, and other electronics. Use it to monitor the energy usage of your TV, control lamps in an office, or anything else you can think of. In order to communicate with the outlet, you'll also need the SmartThings Hub, which allows you to expand and integrate more devices into your system as you desire.")
FeatureProduct.create(feature_id: 21, product_id: 1, additional_info: "This kit includes the Hue Bridge and 3 of their newest generation of full-color Hue Bulbs for the best colors and control of your lighting. LED bulbs like the Samsung Hue use up to 80% less power than stabdard incandescent bulbs, which can save you money and reduce your carbon footprint.")
FeatureProduct.create(feature_id: 21, product_id: 2, additional_info: "If needed, these are the Hue full-color bulbs to expand the Hue Bridge kits so you can control even more lights throughout the house. LED bulbs like the Samsung Hue use up to 80% less power than stabdard incandescent bulbs, which can save you money and reduce your carbon footprint.")
FeatureProduct.create(feature_id: 21, product_id: 3, additional_info: "If needed, these are the Hue full-color bulbs to expand the Hue Bridge kits so you can control even more lights throughout the house. LED bulbs like the Samsung Hue use up to 80% less power than stabdard incandescent bulbs, which can save you money and reduce your carbon footprint.")
FeatureProduct.create(feature_id: 21, product_id: 4, additional_info: "The more Hue Bulbs, the more you can mix things up! Each Hue Bridge can support up to 50 bulbs! LED bulbs like the Samsung Hue use up to 80% less power than stabdard incandescent bulbs, which can save you money and reduce your carbon footprint.")
FeatureProduct.create(feature_id: 22, product_id: 24, additional_info: "The SmartThings Hub is the main brain of the SmartThings brand of smart home automation systems. It is extremely easy to set up, can send alerts directly to your phone, and is compatible with hudreds of devices, allowing you to grow your smart home at the pace most comfortable for you.")
FeatureProduct.create(feature_id: 22, product_id: 26, additional_info: "The SmartThings outlet allows you to control the power to lamps, fans, and other small appliances. Use it to monitor the energy usage of your TV, control your fan, or anything else you can think of. In order to communicate with the outlet, you'll also need the SmartThings Hub, which allows you to expand and integrate more devices into your system as you desire.")
FeatureProduct.create(feature_id: 22, product_id: 27, additional_info: "Easily the most well-known smart thermostat on the market, the Nest thermostat earns its reputation as the most reliable, most advanced smart thermostat out there. It is extremely easy to use and has the best design of any thermostat on the market. It includes a wealth of amazing features, including an advanced AI that can learn your schedule and adjust your temperatures without making you set a schedule explicitly. Combined with the SmartThings Hub and the SmartThings outlet, you can censerve even more energy by only powering fans and other appliances when the temperature reaches a certain threshhold.")
FeatureProduct.create(feature_id: 23, product_id: 30, additional_info: "This H2o Vibe Showerhead has a built-in bluetooth speaker so you can jam out to all your favorite tunes without worrying about damaging your phone.")
FeatureProduct.create(feature_id: 24, product_id: 31, additional_info: "The Rachio Smart Sprinkler Controller gives you the ultimate control over your sprinkler system. It can be combined with other smart systems, such as SmartThings and Amazon Echo, to help you preserve water and take the best care of your lawn, without having to worry about turning on the sprinklers every day.")
FeatureProduct.create(feature_id: 25, product_id: 31, additional_info: "The Rachio Smart Sprinkler Controller gives you the ultimate control over your sprinkler system. It can be combined with other smart systems, such as SmartThings and Amazon Echo, to help you preserve water and take the best care of your lawn, without having to worry about turning on the sprinklers every day. Simply add a weather check with SmartThings or Alexa to disable the sprinklers if the forecast shows rain and you're all set to go!")
FeatureProduct.create(feature_id: 26, product_id: 32, additional_info: "The WORX Landroid is the Roomba of lawns. This intelligent, self-driven lawnmower will take care of your grass for you, so you can enjoy your days instead.")
FeatureProduct.create(feature_id: 27, product_id: 33, additional_info: "The Edyn Garden Sensor can be placed in your garden or flowerbed to keep track of the moisture, light, temperature, and nutrient levels of the soil so you can ensure your plants will be the envy of the neighborhood.")
FeatureProduct.create(feature_id: 28, product_id: 34, additional_info: "The Invoxia Smart Portable Speaker is designed for rugged outdoor use. It features voice commands with Amazon Alexa, internet radio through services like Pandora and Spotify, and can even act as a speakerphone for a phone connected via Bluetooth.")
FeatureProduct.create(feature_id: 29, product_id: 15, additional_info: "The SONOS PLAY:1 speakers are great for easy distributed audio throughout the home. They link up to your WiFi and allow you to choose which speakers you would like to use. Higher versions (such as the PLAY:5) allow for higher sound quality.")
FeatureProduct.create(feature_id: 29, product_id: 14, additional_info: "For larger houses, or houses where the WiFi signal doesn't reach certain rooms you want to play music in, the SONOS BOOST allows you to connect the SONOS speakers to eachother, instead of directly to the WiFi network, meaning you can greatly extend their potential range.")
FeatureProduct.create(feature_id: 29, product_id: 35, additional_info: "Another great option for distributed audio without all the wires is the Bose Soundtouch system. This package comes with 2 incredible Bose speakers that can be connected together wirelessly through your home Wi-Fi so you can play music from your phone or computer throughout the home.")
FeatureProduct.create(feature_id: 30, product_id: 6, additional_info: "")
FeatureProduct.create(feature_id: 30, product_id: 19, additional_info: "")
FeatureProduct.create(feature_id: 30, product_id: 37, additional_info: "")
FeatureProduct.create(feature_id: 31, product_id: 36, additional_info: "")
FeatureProduct.create(feature_id: 31, product_id: 38, additional_info: "")
FeatureProduct.create(feature_id: 32, product_id: 19, additional_info: "")
FeatureProduct.create(feature_id: 32, product_id: 37, additional_info: "")
FeatureProduct.create(feature_id: 33, product_id: 38, additional_info: "")
FeatureProduct.create(feature_id: 34, product_id: 39, additional_info: "")
FeatureProduct.create(feature_id: 35, product_id: 11, additional_info: "")
