# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Category.create([{name: 'Lighting'}])
Category.create([{name: 'Entertainment'}])
Category.create([{name: 'Climate'}])
Category.create([{name: 'Security'}])
Category.create([{name: 'Safety'}])
Category.create([{name: 'Family'}])
Category.create([{name: 'Outdoors'}])
Category.create([{name: 'Location'}])
Category.create([{name: 'Assistive'}])

Feature.create([{description: "I want my lights to change colors when I play music."}])
Feature.create([{description: "I want my lights to turn off automatically when I'm not in the room."}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
Feature.create([{description: ""}])
