# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create( name: 'Star Wars' }, { name: 'Lord of the Rings' )
#   Character.create(name: 'Luke', movie: movies.first)

Category.create(name: 'Lighting')
Category.create(name: 'Entertainment')
Category.create(name: 'Climate')
Category.create(name: 'Security')
Category.create(name: 'Safety')
Category.create(name: 'Family')
Category.create(name: 'Outdoors')
Category.create(name: 'Assistive')

Feature.create(description: "I want my lights to change colors when I play music.")                         #1
Feature.create(description: "I want my lights to turn off automatically when I'm not in the room.")         #2
Feature.create(description: "I want my lights to adjust themselves automatically for my needs.")            #3
Feature.create(description: "I want to see my house live on my cellphone.")                                 #4
Feature.create(description: "I want to keep digital recordings of my house's surroundings.")                #5
Feature.create(description: "I want to lock/unlock my door from anywhere.")                                 #6
Feature.create(description: "I want to see who is at the door from anywhere.")                              #7
Feature.create(description: "I want to stream music throughout my house.")                                  #8
Feature.create(description: "I want to control all of my devices with a single remote.")                    #9
Feature.create(description: "I want to connect all of my media players to a single device.")                #10
Feature.create(description: "I want to access all my entertainment services through a single interface.")   #11
Feature.create(description: "I want to voice control my music and shows.")                                  #12
Feature.create(description: "I want to see and speak with my family and friends from my room.")             #13
Feature.create(description: "I want to be alerted if there is dangerous weather near my home.")             #14
Feature.create(description: "I want to control my house using voice commands.")                             #15
Feature.create(description: "I want my thermostat to adjust itself.")                                       #16
Feature.create(description: "I want to know when there is someone at the door, even if I can't hear them.") #17
Feature.create(description: "I want to know about water leaks as soon as they happen, even when I'm not home.")                                                                                                     #18
Feature.create(description: "I want to moniter my appliances when they're connected.")                      #19
Feature.create(description: "I want my water valve to shut off if it detects a leak.")                      #20
Feature.create(description: "I want a thermostat that learns my habits.")                                   #21
Feature.create(description: "I want to regulate energy usage to save money and the environment.")           #22
Feature.create(description: "I want a fan that only turns on when it's too hot/cold.")                      #23
Feature.create(description: "I want a heater that turns itself on when it gets too cold.")                  #24
Feature.create(description: "I want sprinklers that work automatically.")                                   #25
Feature.create(description: "I want sprinklers that won't turn on if it's going to rain.")                  #26
Feature.create(description: "I want a lawn that mows itself.")                                              #27
Feature.create(description: "I want to know if the plants in my flowerbed/garden are healthy.")             #28
Feature.create(description: "I want to listen to my music outdoors.")                                       #29
Feature.create(description: "I want to play music in several rooms of my home.")                            #30
Feature.create(description: "I want to check in on my kid(s) when I'm not home.")                           #31
Feature.create(description: "I want to check in on my pet(s) when I'm not home.")                           #32
Feature.create(description: "I want to know that my kids are safe when they aren't home.")                  #33
Feature.create(description: "I want to feed my pets remotely.")                                             #34
Feature.create(description: "I want to be alerted if there is a gas leak in my home.")                      #35

CategoryFeature.create(category_id: 1, feature_id: 1)
CategoryFeature.create(category_id: 1, feature_id: 2)
CategoryFeature.create(category_id: 1, feature_id: 3)
CategoryFeature.create(category_id: 1, feature_id: 22)
CategoryFeature.create(category_id: 2, feature_id: 1)
CategoryFeature.create(category_id: 2, feature_id: 8)
CategoryFeature.create(category_id: 2, feature_id: 9)
CategoryFeature.create(category_id: 2, feature_id: 10)
CategoryFeature.create(category_id: 2, feature_id: 11)
CategoryFeature.create(category_id: 2, feature_id: 12)
CategoryFeature.create(category_id: 2, feature_id: 29)
CategoryFeature.create(category_id: 2, feature_id: 30)
CategoryFeature.create(category_id: 3, feature_id: 9)
CategoryFeature.create(category_id: 3, feature_id: 15)
CategoryFeature.create(category_id: 3, feature_id: 16)
CategoryFeature.create(category_id: 3, feature_id: 21)
CategoryFeature.create(category_id: 3, feature_id: 22)
CategoryFeature.create(category_id: 3, feature_id: 23)
CategoryFeature.create(category_id: 3, feature_id: 24)
CategoryFeature.create(category_id: 4, feature_id: 4)
CategoryFeature.create(category_id: 4, feature_id: 5)
CategoryFeature.create(category_id: 4, feature_id: 6)
CategoryFeature.create(category_id: 4, feature_id: 7)
CategoryFeature.create(category_id: 4, feature_id: 8)
CategoryFeature.create(category_id: 4, feature_id: 17)
CategoryFeature.create(category_id: 4, feature_id: 31)
CategoryFeature.create(category_id: 4, feature_id: 32)
CategoryFeature.create(category_id: 4, feature_id: 33)
CategoryFeature.create(category_id: 5, feature_id: 4)
CategoryFeature.create(category_id: 5, feature_id: 9)
CategoryFeature.create(category_id: 5, feature_id: 13)
CategoryFeature.create(category_id: 5, feature_id: 15)
CategoryFeature.create(category_id: 5, feature_id: 18)
CategoryFeature.create(category_id: 5, feature_id: 19)
CategoryFeature.create(category_id: 5, feature_id: 20)
CategoryFeature.create(category_id: 5, feature_id: 31)
CategoryFeature.create(category_id: 5, feature_id: 32)
CategoryFeature.create(category_id: 5, feature_id: 33)
CategoryFeature.create(category_id: 5, feature_id: 35)
CategoryFeature.create(category_id: 5, feature_id: 14)
CategoryFeature.create(category_id: 6, feature_id: 4)
CategoryFeature.create(category_id: 6, feature_id: 5)
CategoryFeature.create(category_id: 6, feature_id: 6)
CategoryFeature.create(category_id: 6, feature_id: 7)
CategoryFeature.create(category_id: 6, feature_id: 13)
CategoryFeature.create(category_id: 6, feature_id: 14)
CategoryFeature.create(category_id: 6, feature_id: 30)
CategoryFeature.create(category_id: 6, feature_id: 31)
CategoryFeature.create(category_id: 6, feature_id: 32)
CategoryFeature.create(category_id: 6, feature_id: 33)
CategoryFeature.create(category_id: 6, feature_id: 34)
CategoryFeature.create(category_id: 7, feature_id: 14)
CategoryFeature.create(category_id: 7, feature_id: 17)
CategoryFeature.create(category_id: 7, feature_id: 25)
CategoryFeature.create(category_id: 7, feature_id: 26)
CategoryFeature.create(category_id: 7, feature_id: 27)
CategoryFeature.create(category_id: 7, feature_id: 28)
CategoryFeature.create(category_id: 7, feature_id: 29)
CategoryFeature.create(category_id: 8, feature_id: 2)
CategoryFeature.create(category_id: 8, feature_id: 3)
CategoryFeature.create(category_id: 8, feature_id: 5)
CategoryFeature.create(category_id: 8, feature_id: 6)
CategoryFeature.create(category_id: 8, feature_id: 7)
CategoryFeature.create(category_id: 8, feature_id: 12)
CategoryFeature.create(category_id: 8, feature_id: 13)
CategoryFeature.create(category_id: 8, feature_id: 14)
CategoryFeature.create(category_id: 8, feature_id: 15)
CategoryFeature.create(category_id: 8, feature_id: 17)

Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01KJYSOHM&asins=B01KJYSOHM&linkId=0a6568ace395f36522b262892dece36f&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01KJYSOHM/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01KJYSOHM&linkCode=as2&tag=hassurunous-20&linkId=b83a84fb80edae108b0ba3ff93354e88">Philips 464503 Hue White and Color A19 LED Bulb, 3rd Generation with Richer Colors for IOS and Android</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01KJYSOHM" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01KJYSOHM/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01KJYSOHM&linkCode=as2&tag=hassurunous-20&linkId=21137bfb913fd620419ea7b960744560"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01KJYSOHM&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01KJYSOHM" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Philips 464503 Hue White and Color A19 LED Bulb, 3rd Generation with Richer Colors for IOS and Android')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01M9AU8MB&asins=B01M9AU8MB&linkId=b76368d574ab3fbcf12325cc15088797&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01M9AU8MB/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01M9AU8MB&linkCode=as2&tag=hassurunous-20&linkId=02189854401e7d212af1f44b3cf0e6bf">Philips - Hue White and Color Ambiance A19 Smart LED Light Bulb - Multicolor, 3rd Generation</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01M9AU8MB" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01M9AU8MB/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01M9AU8MB&linkCode=as2&tag=hassurunous-20&linkId=d6f430c1af58a10c8c46c964fb2c06bc"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01M9AU8MB&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01M9AU8MB" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Philips - Hue White and Color Ambiance A19 Smart LED Light Bulb - Multicolor, 3rd Generation')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01ESW34RQ&asins=B01ESW34RQ&linkId=56e9e5a4f75098cbda2bf321dc82a4a9&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01ESW34RQ/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01ESW34RQ&linkCode=as2&tag=hassurunous-20&linkId=7032a0effbd9021e03fedb012c9f07bb">Philips 461020 Hue White Ambiance Single A19 Bulb, Works with Amazon Alexa</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01ESW34RQ" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01ESW34RQ/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01ESW34RQ&linkCode=as2&tag=hassurunous-20&linkId=3208294786e271865af71ccbb3e91463"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01ESW34RQ&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01ESW34RQ" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Philips 461020 Hue White Ambiance Single A19 Bulb, Works with Amazon Alexa')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01KJYSOGI&asins=B01KJYSOGI&linkId=0673132c8c04380dd0432ea372217320&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01KJYSOGI/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01KJYSOGI&linkCode=as2&tag=hassurunous-20&linkId=0508013579157e7459fc9ef9281f8da3">Philips 464602 Hue Motion Sensor</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01KJYSOGI" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01KJYSOGI/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01KJYSOGI&linkCode=as2&tag=hassurunous-20&linkId=e89e7e1ba7fc6ac82ceb0952118b7e81"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01KJYSOGI&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01KJYSOGI" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Philips 464602 Hue Motion Sensor')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00M5BX5P4&asins=B00M5BX5P4&linkId=c46c3574956b4b9e295a68cd103410b9&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00M5BX5P4/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00M5BX5P4&linkCode=as2&tag=hassurunous-20&linkId=a95080438243cda3755f7160c9d722d4">D-Link Pan &amp; Tilt Wi-Fi Camera (DCS-5009L)</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00M5BX5P4" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00M5BX5P4/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00M5BX5P4&linkCode=as2&tag=hassurunous-20&linkId=f61c7ac09a46d9afe565a687ab525e39"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00M5BX5P4&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00M5BX5P4" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'D-Link Pan & Tilt Wi-Fi Camera (DCS-5009L)')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00F0R9V76&asins=B00F0R9V76&linkId=4db300249ac30e9c49bd4cd11e11c19c&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00F0R9V76/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00F0R9V76&linkCode=as2&tag=hassurunous-20&linkId=2db4c4fe1acf8c71f68938b20059d49a">D-Link Camera Video Recorder mydlink-Enabled (DNR-202L)</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00F0R9V76" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00F0R9V76/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00F0R9V76&linkCode=as2&tag=hassurunous-20&linkId=bb299fc94a84c95daf033aab5f1edd78"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00F0R9V76&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00F0R9V76" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'D-Link Camera Video Recorder mydlink-Enabled (DNR-202L)')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B004P8K24W&asins=B004P8K24W&linkId=3bca86489d239ec7f26aaef92ff2fa18&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B004P8K24W/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B004P8K24W&linkCode=as2&tag=hassurunous-20&linkId=0af4861557bdbbdded0a56b38ff1cd78">D-Link Day &amp; Night Wi-Fi Camera with Remote Viewing (DCS-932L)</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B004P8K24W" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B004P8K24W/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B004P8K24W&linkCode=as2&tag=hassurunous-20&linkId=b11cb2e39fda4cdf30bc4c7d943bb476"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B004P8K24W&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B004P8K24W" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'D-Link Day & Night Wi-Fi Camera with Remote Viewing (DCS-932L)')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01HO9XZR4&asins=B01HO9XZR4&linkId=4317c46ccebdcd75fac6fe496e69b493&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01HO9XZR4/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01HO9XZR4&linkCode=as2&tag=hassurunous-20&linkId=67e91aa3622ac8052debc4cf0bcfa341">D-Link HD Wi-Fi Camera (DCS-936L)</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01HO9XZR4" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01HO9XZR4/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01HO9XZR4&linkCode=as2&tag=hassurunous-20&linkId=d22745e8c5edf94cc4ae28dcf70b0202"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01HO9XZR4&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01HO9XZR4" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'D-Link HD Wi-Fi Camera (DCS-936L)')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01KZRPNIQ&asins=B01KZRPNIQ&linkId=a99ccdd2f280c94bb748c318cb107d3a&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01KZRPNIQ/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01KZRPNIQ&linkCode=as2&tag=hassurunous-20&linkId=97779f54e3a42de3abe7e3fdd9bb85d8">Denon AVRX4300H 9.2 Channel Full 4K Ultra HD AV Receiver with Built-in HEOS wireless technology featuring Bluetooth and Wi-Fi</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01KZRPNIQ" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01KZRPNIQ/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01KZRPNIQ&linkCode=as2&tag=hassurunous-20&linkId=d68be0bf398f317eb683816cc4dcac4a"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01KZRPNIQ&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01KZRPNIQ" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Denon AVRX4300H 9.2 Channel Full 4K Ultra HD AV Receiver with Built-in HEOS wireless technology featuring Bluetooth and Wi-Fi')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B001CROHX6&asins=B001CROHX6&linkId=05ccdd3e976d9a76b66c2b7cc4f8be8d&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B001CROHX6/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B001CROHX6&linkCode=as2&tag=hassurunous-20&linkId=84540356918b17c9315f6887fc5a3f2f">Sonos CONNECT Wireless Receiver Component for Streaming Music</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B001CROHX6" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B001CROHX6/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B001CROHX6&linkCode=as2&tag=hassurunous-20&linkId=c7557dae1a78d18a1a5319b52645b304"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B001CROHX6&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B001CROHX6" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Sonos CONNECT Wireless Receiver Component for Streaming Music')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00ZV9RDKK&asins=B00ZV9RDKK&linkId=a192882499c73b53cf9d8817a9f99a89&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00ZV9RDKK/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00ZV9RDKK&linkCode=as2&tag=hassurunous-20&linkId=571993c78f46d48a750ba541334ff6f2">All-New Fire TV Stick with Alexa Voice Remote | Streaming Media Player</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00ZV9RDKK" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00ZV9RDKK/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00ZV9RDKK&linkCode=as2&tag=hassurunous-20&linkId=2edc111805d40ac79c9cd741317e5eda"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00ZV9RDKK&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00ZV9RDKK" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'All-New Fire TV Stick with Alexa Voice Remote | Streaming Media Player')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B014PDFP9S&asins=B014PDFP9S&linkId=48b5f5678bbcb844f238b618b9942c56&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00N3RFCBE/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00N3RFCBE&linkCode=as2&tag=hassurunous-20&linkId=171ee947bb7064d3d2bce988c311ccdb">Logitech Harmony Ultimate Home Touch Screen Programmable Remote for 15 Home Entertainment and Automation Devices (black)</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00N3RFCBE" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00N3RFCBE/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00N3RFCBE&linkCode=as2&tag=hassurunous-20&linkId=29ed12827e7941a509da717570db1576"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00N3RFCBE&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00N3RFCBE" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Logitech Harmony Ultimate Home Touch Screen Programmable Remote for 15 Home Entertainment and Automation Devices (black)')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01ENWYKRE&asins=B01ENWYKRE&linkId=37809951ced3483b330693999777ee6f&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01ENWYKRE/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01ENWYKRE&linkCode=as2&tag=hassurunous-20&linkId=1c19163fc6dd3ba58699e8d1484b071b">Nucleus Anywhere Intercom with Amazon Alexa, 2 Pack</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01ENWYKRE" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01ENWYKRE/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01ENWYKRE&linkCode=as2&tag=hassurunous-20&linkId=6f61339cb9da98013866dfca9d865df6"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01ENWYKRE&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01ENWYKRE" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Nucleus Anywhere Intercom with Amazon Alexa, 2 Pack')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01MA4IOQK&asins=B01MA4IOQK&linkId=540a56df9fb873d11bafcbaf003aac18&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01ENWYKRE/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01ENWYKRE&linkCode=as2&tag=hassurunous-20&linkId=474a896641ba4cf2d5ed4b4a1842cfb4">Nucleus Anywhere Intercom with Amazon Alexa, 2 Pack</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01ENWYKRE" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01ENWYKRE/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01ENWYKRE&linkCode=as2&tag=hassurunous-20&linkId=17ea6ed8a32b88dcdea76780a2f44578"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01ENWYKRE&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01ENWYKRE" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'iMCO CoWatch with Amazon Alexa, Silver')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01DFKC2SO&asins=B01DFKC2SO&linkId=05c2996681c18381c3364c14d865bdda&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01DFKC2SO/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01DFKC2SO&linkCode=as2&tag=hassurunous-20&linkId=6af7a063c2d277f073d7b6b483dd16df">All-New Echo Dot (2nd Generation) - Black</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01DFKC2SO" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01DFKC2SO/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01DFKC2SO&linkCode=as2&tag=hassurunous-20&linkId=66724c73578ee51eeab8c030b819cb85"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01DFKC2SO&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01DFKC2SO" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'All-New Echo Dot (2nd Generation) - Black')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01LTHM8LG&asins=B01LTHM8LG&linkId=7a94501dd6532287ae4146d5b9bd5b4b&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01LTHM8LG/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01LTHM8LG&linkCode=as2&tag=hassurunous-20&linkId=1aa6e6618aa495abaf506c313107cfcf">Lyric T5 Wi-Fi Thermostat, Works with Apple HomeKit and Amazon Alexa</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01LTHM8LG" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01LTHM8LG/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01LTHM8LG&linkCode=as2&tag=hassurunous-20&linkId=ccf2bb0f777551b35cd38c7d9894858f"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01LTHM8LG&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01LTHM8LG" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Lyric T5 Wi-Fi Thermostat, Works with Apple HomeKit and Amazon Alexa')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00MOIYIN6&asins=B00MOIYIN6&linkId=be8dcdfc13139d41321d1fd8ef555191&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00MOIYIN6/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00MOIYIN6&linkCode=as2&tag=hassurunous-20&linkId=5a774e3f0ca26eee4fd7309b179aaf09">Samsung SmartThings Water Leak Sensor</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00MOIYIN6" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00MOIYIN6/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00MOIYIN6&linkCode=as2&tag=hassurunous-20&linkId=4cb0d28837eddc60b8cea0f1abc779f5"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00MOIYIN6&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00MOIYIN6" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Samsung SmartThings Water Leak Sensor')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B010NZV0GE&asins=B010NZV0GE&linkId=36e504e69e9d6863cf4ded3c5e5a7cfc&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B010NZV0GE/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B010NZV0GE&linkCode=as2&tag=hassurunous-20&linkId=51dccf980fb9a38e1b1d2f161c69bb63">Samsung SmartThings Hub- White</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B010NZV0GE" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B010NZV0GE/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B010NZV0GE&linkCode=as2&tag=hassurunous-20&linkId=afd0983c21f4ad8fca86c7d40d5a9b2a"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B010NZV0GE&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B010NZV0GE" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Samsung SmartThings Hub - White')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01LE9OD3A&asins=B01LE9OD3A&linkId=d3d3ecc922aacde6312a5da171b9ba19&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01LE9OD3A/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01LE9OD3A&linkCode=as2&tag=hassurunous-20&linkId=16f82476eb9f8cfc1cce052141fd0252">Z-Wave 3/4" Valve Water Control Valve by Leak Gopher, Z-Wave Plus, NSF Certified, USA MADE</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01LE9OD3A" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01LE9OD3A/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01LE9OD3A&linkCode=as2&tag=hassurunous-20&linkId=d9e297016c31147c69ddc653840566e5"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01LE9OD3A&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01LE9OD3A" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Z-Wave 3/4" Valve Water Control Valve by Leak Gopher, Z-Wave Plus, NSF Certified, USA MADE')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00MI5V5N6&asins=B00MI5V5N6&linkId=7947954d63647416273e9669824e6bbc&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00MI5V5N6/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00MI5V5N6&linkCode=as2&tag=hassurunous-20&linkId=c12689838e75d787d03c08f7e2372477">Samsung SmartThings Outlet, Works with Amazon Alexa</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00MI5V5N6" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00MI5V5N6/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00MI5V5N6&linkCode=as2&tag=hassurunous-20&linkId=41a576e346d5082fd3bbbe6785aea50a"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00MI5V5N6&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00MI5V5N6" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Samsung SmartThings Outlet, Works with Amazon Alexa')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B0131RG6VK&asins=B0131RG6VK&linkId=d897866faea9fc5b7f08f44a8a69b2b1&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B0131RG6VK/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B0131RG6VK&linkCode=as2&tag=hassurunous-20&linkId=bf2abc03e6b45196d39ba70416dd666c">Nest Learning Thermostat, 3rd Generation, Works with Amazon Alexa</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B0131RG6VK" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B0131RG6VK/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B0131RG6VK&linkCode=as2&tag=hassurunous-20&linkId=7dd69c0f08139de941267d316b27690b"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B0131RG6VK&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B0131RG6VK" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Nest Learning Thermostat, 3rd Generation, Works with Amazon Alexa')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01DFKC2SO&asins=B01DFKC2SO&linkId=1b6b186360903e24d9360c1e606e6363&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01DFKC2SO/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01DFKC2SO&linkCode=as2&tag=hassurunous-20&linkId=85ef39bf9bd3148c2bbf5751f55e34c1">All-New Echo Dot (2nd Generation) - Black</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01DFKC2SO" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01DFKC2SO/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01DFKC2SO&linkCode=as2&tag=hassurunous-20&linkId=f7f908ae88852b860022b0acb618690d"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01DFKC2SO&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01DFKC2SO" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'All-New Echo Dot (2nd Generation) - Black')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B001EDVU6K&asins=B001EDVU6K&linkId=aaa9ee7518f81bb855664027faf7c42c&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B001EDVU6K/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B001EDVU6K&linkCode=as2&tag=hassurunous-20&linkId=f6685417bed92975673c77fea0d49745">Vornado TVH600 Whole Room Vortex Heater, Automatic Climate Control</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B001EDVU6K" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B001EDVU6K/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B001EDVU6K&linkCode=as2&tag=hassurunous-20&linkId=3bfa935f7567cba0d0d001c6293d709c"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B001EDVU6K&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B001EDVU6K" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Vornado TVH600 Whole Room Vortex Heater, Automatic Climate Control')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00F4BHC24&asins=B00F4BHC24&linkId=9eeba7debd1ee52a6e3352632a2e9267&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>
', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00F4BHC24/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00F4BHC24&linkCode=as2&tag=hassurunous-20&linkId=e2e5c7c7a240dce51829f7f20bfadba3">Lifesmart Large Room 6 Element Infrared Heater w/Remote</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00F4BHC24" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00F4BHC24/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00F4BHC24&linkCode=as2&tag=hassurunous-20&linkId=c2246de4b0d3f667a03d28dffc1de045"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00F4BHC24&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00F4BHC24" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
', name: 'Lifesmart Large Room 6 Element Infrared Heater w/Remote')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01D1NMLJU&asins=B01D1NMLJU&linkId=d0170003671fda9c45ed083b45e913b0&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01D1NMLJU/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01D1NMLJU&linkCode=as2&tag=hassurunous-20&linkId=6572a3d097a0623347fd317bae748d46">Rachio Smart Sprinkler Controller, 8 Zone 2nd Generation, Works with Alexa</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01D1NMLJU" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01D1NMLJU/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01D1NMLJU&linkCode=as2&tag=hassurunous-20&linkId=1fa6698b40583ba765601e8448bdbbe9"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01D1NMLJU&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01D1NMLJU" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Rachio Smart Sprinkler Controller, 8 Zone 2nd Generation, Works with Alexa')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00SJEUFF4&asins=B00SJEUFF4&linkId=bbce53e69fec826c4fe4d0736b2baba6&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00SJEUFF4/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00SJEUFF4&linkCode=as2&tag=hassurunous-20&linkId=99652351149c387e199f7f49c56ab060">WORX Landroid Robotic Lawn Mower, 28-volt WG794</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00SJEUFF4" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00SJEUFF4/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00SJEUFF4&linkCode=as2&tag=hassurunous-20&linkId=2394e8bad324825de7d51ea55c38ad92"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00SJEUFF4&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00SJEUFF4" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'WORX Landroid Robotic Lawn Mower, 28-volt WG794')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00FOM2YDU&asins=B00FOM2YDU&linkId=14502410f6d334b6ca89ae54e8800490&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00FOM2YDU/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00FOM2YDU&linkCode=as2&tag=hassurunous-20&linkId=a07fcc161ff4ae5a35b4d2588e979b77">Parrot Flower Power - Wireless Indoor/Outdoor Bluetooth Smart Plant Sensor with Free dedicated App - Blue</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00FOM2YDU" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00FOM2YDU/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00FOM2YDU&linkCode=as2&tag=hassurunous-20&linkId=abc29854fb3ad8ee86510a068de03888"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00FOM2YDU&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00FOM2YDU" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Parrot Flower Power - Wireless Indoor/Outdoor Bluetooth Smart Plant Sensor with Free dedicated App - Blue')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B017WL4N84&asins=B017WL4N84&linkId=cc08e87a601d2219387bfd01575c03de&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B017WL4N84/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B017WL4N84&linkCode=as2&tag=hassurunous-20&linkId=02d3a5afe0d51de85173a4562bded796">Invoxia Smart Portable Speaker with Amazon Alexa, Blue</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B017WL4N84" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B017WL4N84/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B017WL4N84&linkCode=as2&tag=hassurunous-20&linkId=612b60ef844f1467ce4782cbea4ae284"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B017WL4N84&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B017WL4N84" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Invoxia Smart Portable Speaker with Amazon Alexa, Blue')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B0155N973M&asins=B0155N973M&linkId=7672edba5b8da3002112f7e6233d6f64&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B0155N973M/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B0155N973M&linkCode=as2&tag=hassurunous-20&linkId=70eb12ed4d45b6baa149946b13d7bf61">Bose SoundTouch 10 Wireless Music System Bundle 2-Pack - Black</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B0155N973M" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B0155N973M/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B0155N973M&linkCode=as2&tag=hassurunous-20&linkId=19181ea07b48f441365555b2aa030c90"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B0155N973M&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B0155N973M" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Bose SoundTouch 10 Wireless Music System Bundle 2-Pack - Black')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B00JGWN8O8&asins=B00JGWN8O8&linkId=a7b64593018052e321dd58b18ae4d143&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B00JGWN8O8/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00JGWN8O8&linkCode=as2&tag=hassurunous-20&linkId=4d088d2cb17a51deba49fe73662e17df">Petcube Camera | 720p Video, 2-Way Audio, and Built-in Laser Toy</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00JGWN8O8" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B00JGWN8O8/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00JGWN8O8&linkCode=as2&tag=hassurunous-20&linkId=d9e794553410f04f0edb21253656ef0d"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00JGWN8O8&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B00JGWN8O8" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Petcube Camera | 720p Video, 2-Way Audio, and Built-in Laser Toy')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01N63MFAB&asins=B01N63MFAB&linkId=9a31080d9f54b22173c388e8545ffdd4&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01N63MFAB/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01N63MFAB&linkCode=as2&tag=hassurunous-20&linkId=e4cdde9d9800cedef51ed3f02eb23064">MX-LOCare Mobile Personal Emergency Response GPS Watch Wifi Tracking Safety SmartWatch Tracker for Elderly, Kids, Teens, Autism, Alzheimer</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01N63MFAB" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01N63MFAB/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01N63MFAB&linkCode=as2&tag=hassurunous-20&linkId=922fedcc579ea626bc88a7111f1d1a6e"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01N63MFAB&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01N63MFAB" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'MX-LOCare Mobile Personal Emergency Response GPS Watch Wifi Tracking Safety SmartWatch Tracker for Elderly, Kids, Teens, Autism, Alzheimer')
Product.create(frame_link: '<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hassurunous-20&marketplace=amazon&region=US&placement=B01M7UMW0O&asins=B01M7UMW0O&linkId=a70b059e757e1f8da895712db681a314&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff"></iframe>', text_link: '<a target="_blank" href="https://www.amazon.com/gp/product/B01M7UMW0O/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01M7UMW0O&linkCode=as2&tag=hassurunous-20&linkId=e75b7ce3699f5661a4193bb590a6faf6">Smart Pet Feeder, Automatic Pet Feeder for Dogs and Cats, Built in 1 Million Pixels Webcam&amp;Wi-Fi, 4.3L Food Tank, Compatible with iOS/Android or Other Smart Devices,App Feeder-L11.8xW9.6xH14.9in</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01M7UMW0O" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', image_link: '<a target="_blank"  href="https://www.amazon.com/gp/product/B01M7UMW0O/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01M7UMW0O&linkCode=as2&tag=hassurunous-20&linkId=671b24d8fe19078707ed2569fbf5cb42"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01M7UMW0O&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL160_&tag=hassurunous-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=hassurunous-20&l=am2&o=1&a=B01M7UMW0O" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />', name: 'Smart Pet Feeder, Automatic Pet Feeder for Dogs and Cats, Built in 1 Million Pixels Webcam & Wi-Fi, 4.3L Food Tank, Compatible with iOS/Android or Other Smart Devices, App Feeder-L11.8xW9.6xH14.9in')
